
#ifndef _ERROR_CODE_H_
#define _ERROR_CODE_H_

enum EErrorCode
{
	ERR_SUCCESS = 1,
	ERR_FAILED = 2,

	ERR_LOGIN_FAILED_BY_RELAY = 1001,

	ERR_BUILDING_NOT_EXIST = 2001,
	ERR_BUILDING_TYPE_NOT_EXIST = 2002,
	ERR_BUILDING_LOCK = 2003,
	ERR_BUILDING_SAME_INDEX = 2004,
	ERR_BUILDING_RESOURCE_NOT_ENOUGH = 2005,
	ERR_BUILDING_INCOME_TOO_SHORT = 2006,
};


#endif // !_ERROR_CODE_H_

